# Generated by Django 5.2.1 on 2025-09-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='support_phase',
            field=models.CharField(choices=[('training', 'Training'), ('prototyping', 'Prototyping'), ('testing', 'Testing'), ('commercialization', 'Commercialization')], max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='usage_domain',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('mechanical', 'Mechanical'), ('iot', 'IoT'), ('robotics', 'Robotics'), ('software', 'Software')], max_length=100),
        ),
    ]
