# Generated by Django 5.2.5 on 2025-08-26 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('affiliation', models.CharField(choices=[('cs', 'Computer Science'), ('se', 'Software Engineering'), ('eng', 'Engineering'), ('other', 'Other')], max_length=100)),
                ('specialization', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware'), ('business', 'Business')], max_length=100)),
                ('cross_skill_trained', models.BooleanField(default=False)),
                ('institution', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_on_project', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('contributor', 'Contributor')], max_length=100)),
                ('skill_role', models.CharField(choices=[('developer', 'Developer'), ('engineer', 'Engineer'), ('designer', 'Designer'), ('business_lead', 'Business Lead')], max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='participants.participant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participants', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'participant')},
            },
        ),
    ]
