# Generated by Django 5.2.1 on 2025-09-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectParticipant',
        ),
    ]
