# Generated by Django 5.2.5 on 2025-08-26 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={},
        ),
        migrations.RemoveField(
            model_name='program',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title',
        ),
        migrations.AddField(
            model_name='program',
            name='focus_areas',
            field=models.CharField(default='automation', help_text='Domains such as IoT, automation, renewable energy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(default='first program', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='national_alignment',
            field=models.CharField(default='NDPIII', help_text='Link to NDPIII, Roadmap, or 4IR goals', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='phases',
            field=models.CharField(default='Collaboratin', help_text='Cross-Skilling, Collaboration, etc.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
